### ISSUE TITLE
Improve performance under alpine linux

### ISSUE THREAD

**Issue by nicolas-duteil-nova** [ctn-malone/quickjs-cross-compiler#1]
Hi, could you please take a look at https://github.com/bellard/quickjs/pull/239 ?
It improves the behaviour in alpine containers (where looping through all fds is quite inefficient)
Let me know if you need more informations

**Comment by ctn-malone** [comment]
@nicolas-duteil-nova Feel free to open a PR. This project is focused on running musl based quickjs, so as long as your PR improves performances, I'll gladly merge it

**Comment by nicolasduteil** [comment]
Running `exec['date']` 100 times in a loop yields following values

fd_max(65535) : ~ 600ms
fd_max(1024) : ~ 200ms
fd_max(/proc): ~ 190ms
